version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: django-docker:0.0.1
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file: ./docker/dev/.env
 